import logging
import os
from typing import Dict, Any

logger = logging.getLogger(__name__)

# ── Supabase scaffold code injected into generated projects ──────────
_SUPABASE_JS = """\
// supabase.js — auto-generated by DreamAgent Builder
import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js/+esm';

const SUPABASE_URL = '{SUPABASE_URL}';
const SUPABASE_ANON_KEY = '{SUPABASE_ANON_KEY}';

export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

// Auth helpers
export const signUp = (email, password) =>
  supabase.auth.signUp({ email, password });

export const signIn = (email, password) =>
  supabase.auth.signInWithPassword({ email, password });

export const signOut = () => supabase.auth.signOut();

export const getUser = () => supabase.auth.getUser();
"""

_SUPABASE_BACKEND_PY = """\
# supabase_backend.py — auto-generated by DreamAgent Builder
import os
from supabase import create_client

SUPABASE_URL = os.getenv("SUPABASE_URL", "{SUPABASE_URL}")
SUPABASE_KEY = os.getenv("SUPABASE_SERVICE_KEY", "{SUPABASE_ANON_KEY}")

sb = create_client(SUPABASE_URL, SUPABASE_KEY)

def get_db():
    \"\"\"Return Supabase client (dependency-injected in FastAPI routes).\"\"\"
    return sb
"""

# ── Tavily scaffold code ──────────────────────────────────────────────
_TAVILY_PY = """\
# tavily_search.py — auto-generated by DreamAgent Builder
import os
from tavily import TavilyClient

TAVILY_API_KEY = os.getenv("TAVILY_API_KEY", "{TAVILY_API_KEY}")
tavily = TavilyClient(api_key=TAVILY_API_KEY)

def web_search(query: str, max_results: int = 5):
    \"\"\"Perform a web search and return structured results.\"\"\"
    return tavily.search(query=query, search_depth="basic", max_results=max_results)

def news_search(query: str, max_results: int = 5):
    \"\"\"Perform a news search.\"\"\"
    return tavily.search(query=query, topic="news", max_results=max_results)
"""

# ── Stripe scaffold code ──────────────────────────────────────────────
_STRIPE_PY = """\
# stripe_payments.py — auto-generated by DreamAgent Builder
import os
import stripe

stripe.api_key = os.getenv("STRIPE_API_KEY", "")

def create_checkout(price_id: str, success_url: str, cancel_url: str):
    \"\"\"Create a Stripe Checkout Session.\"\"\"
    session = stripe.checkout.Session.create(
        mode="subscription",
        line_items=[{"price": price_id, "quantity": 1}],
        success_url=success_url,
        cancel_url=cancel_url,
    )
    return {"session_id": session.id, "url": session.url}

def verify_webhook(payload: bytes, sig_header: str):
    \"\"\"Verify incoming Stripe webhook.\"\"\"
    secret = os.getenv("STRIPE_WEBHOOK_SECRET", "")
    return stripe.Webhook.construct_event(payload, sig_header, secret)
"""

_STRIPE_JS = """\
// stripe-client.js — auto-generated by DreamAgent Builder
// Include Stripe.js in your HTML: <script src="https://js.stripe.com/v3/"></script>

const stripe = Stripe('{STRIPE_PUBLISHABLE_KEY}');

async function startCheckout(priceId) {
  const response = await fetch('/api/create-checkout-session', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ price_id: priceId }),
  });
  const { url } = await response.json();
  window.location.href = url;
}
"""


class ConnectionRegistry:
    def __init__(self):
        self.registry = {
            "sqlite": self.sqlite,
            "postgresql": self.postgresql,
            "mongodb": self.mongodb,
            "notion": self.notion,
            "webfetch": self.webfetch,
            # ── New integrations ──
            "supabase": self.supabase,
            "tavily": self.tavily,
            "stripe": self.stripe,
        }

    def apply(self, name: str, context: Dict[str, Any]):
        if name in self.registry:
            logger.info(f"[Connections] Applying scaffold: {name}")
            try:
                self.registry[name](context)
            except Exception as e:
                logger.error(f"[Connections] Failed to apply {name}: {e}", exc_info=True)
        else:
            logger.warning(f"[Connections] Unknown connection type: {name}")

    # ── Existing connections ───────────────────────────────────────────

    def sqlite(self, ctx: Dict[str, Any]):
        pass  # existing SQLite scaffold

    def postgresql(self, ctx: Dict[str, Any]):
        pass  # existing PostgreSQL scaffold

    def mongodb(self, ctx: Dict[str, Any]):
        pass  # existing MongoDB scaffold

    def notion(self, ctx: Dict[str, Any]):
        pass  # existing Notion scaffold

    def webfetch(self, ctx: Dict[str, Any]):
        pass  # existing webfetch scaffold

    # ── Supabase ───────────────────────────────────────────────────────

    def supabase(self, ctx: Dict[str, Any]):
        """Inject Supabase client scaffolding into the generated project."""
        path = ctx.get("path", "")
        files: Dict[str, str] = ctx.get("files", {})

        supabase_url = os.getenv("SUPABASE_URL", "YOUR_SUPABASE_URL")
        supabase_key = os.getenv("SUPABASE_ANON_KEY", "YOUR_SUPABASE_ANON_KEY")

        # Frontend JS client
        js_code = _SUPABASE_JS.replace("{SUPABASE_URL}", supabase_url).replace(
            "{SUPABASE_ANON_KEY}", supabase_key
        )
        files["supabase.js"] = js_code

        # Python backend helper
        py_code = _SUPABASE_BACKEND_PY.replace("{SUPABASE_URL}", supabase_url).replace(
            "{SUPABASE_ANON_KEY}", supabase_key
        )
        files["backend/supabase_backend.py"] = py_code

        # Write files to disk if path is provided
        if path:
            _write_file(path, "supabase.js", js_code)
            _write_file(path, "backend/supabase_backend.py", py_code)

        logger.info("[Connections] ✅ Supabase scaffold injected.")

    # ── Tavily ────────────────────────────────────────────────────────

    def tavily(self, ctx: Dict[str, Any]):
        """Inject Tavily search scaffolding into the generated project."""
        path = ctx.get("path", "")
        files: Dict[str, str] = ctx.get("files", {})

        tavily_key = os.getenv("TAVILY_API_KEY", "YOUR_TAVILY_API_KEY")
        py_code = _TAVILY_PY.replace("{TAVILY_API_KEY}", tavily_key)
        files["backend/tavily_search.py"] = py_code

        if path:
            _write_file(path, "backend/tavily_search.py", py_code)

        logger.info("[Connections] ✅ Tavily scaffold injected.")

    # ── Stripe ────────────────────────────────────────────────────────

    def stripe(self, ctx: Dict[str, Any]):
        """Inject Stripe payment scaffolding into the generated project."""
        path = ctx.get("path", "")
        files: Dict[str, str] = ctx.get("files", {})

        publishable_key = os.getenv("STRIPE_PUBLISHABLE_KEY", "YOUR_STRIPE_PUBLISHABLE_KEY")
        py_code = _STRIPE_PY
        js_code = _STRIPE_JS.replace("{STRIPE_PUBLISHABLE_KEY}", publishable_key)

        files["backend/stripe_payments.py"] = py_code
        files["stripe-client.js"] = js_code

        if path:
            _write_file(path, "backend/stripe_payments.py", py_code)
            _write_file(path, "stripe-client.js", js_code)

        logger.info("[Connections] ✅ Stripe scaffold injected.")


def _write_file(base_path: str, relative_path: str, content: str):
    """Safe helper to write a scaffolded file to disk."""
    try:
        full_path = os.path.join(base_path, relative_path)
        os.makedirs(os.path.dirname(full_path), exist_ok=True)
        with open(full_path, "w", encoding="utf-8") as f:
            f.write(content)
        logger.debug(f"[Connections] Wrote: {full_path}")
    except Exception as e:
        logger.warning(f"[Connections] Could not write {relative_path}: {e}")


connections_registry = ConnectionRegistry()

