"""
backend/agents/guardrail_agent.py

Final Output Guardrail Agent.
Responsible for checking factual correctness, logical consistency, citation presence, and format compliance.
Implements Tasks 1 & 8 from the DreamAgent Task Pack.
"""

import json
import logging
import re
from typing import Dict, Any, List

from .base_agent import BaseAgent

logger = logging.getLogger(__name__)

GUARDRAIL_SYSTEM = """You are the Truth-Grade Citation Enforcer & Validator Agent.
Your job is to act as the final gatekeeper for output before it is shown to the user.
You must analyze the provided text and strictly enforce these rules:

1. Factual Correctness & Citation Presence: Every factual claim MUST have a valid '[Source: URL]' citation. 
2. Grouped Citations: Grouped citations like '(Source: Google, Adobe)' or '[Source: http://site1, http://site2]' are FORBIDDEN. They must be ungrouped into distinct claims with individual citations.
3. Logical Consistency: The output must be logically consistent and not contradict itself.
4. Format Compliance: The text must be clean, readable markdown.

Input will:
- Provide Raw Context URLs (The upstream data URLs from which facts should be derived)
- Provide Generated Output (The draft text to evaluate)

Return a structured JSON output exactly matching this schema:
{
  "valid": boolean, // True if the output meets all strict standards without modification.
  "issues_found": ["list of strings describing specific issues"],
  "fixed_output": "string containing the completely rewritten, fully compliant output. Ungroup citations here and add [⚠️ Missing verifiable source URL] if a claim has no valid source from the context."
}
Only output the raw JSON. Do not use markdown wrappers like ```json.
"""

class GuardrailValidatorAgent(BaseAgent):
    def __init__(self, llm, memory=None, tools=None):
        super().__init__(llm, memory, tools, role="guardrail")

    async def validate(self, draft_output: str, raw_context_urls: List[str] = None, mode: str = "soft") -> Dict[str, Any]:
        """
        Validate and optionally fix the draft output.
        
        Args:
            draft_output: The draft response generated by previous agents.
            raw_context_urls: List of valid URLs provided by upstream systems (e.g. search).
            mode: "strict" (rejects if not perfect) or "soft" (attempts to fix and pass it through).
            
        Returns:
            Dict containing valid status, issues, and the final output.
        """
        if raw_context_urls is None:
            raw_context_urls = []
            
        context_str = ", ".join(raw_context_urls) if raw_context_urls else "No external context URLs provided."
        
        prompt = (
            f"RAW CONTEXT URLs: {context_str}\n\n"
            f"DRAFT OUTPUT TO EVALUATE:\n{draft_output}\n"
            "Evaluate this draft strictly according to your system prompt instructions."
        )

        response = await self.think(prompt, system=GUARDRAIL_SYSTEM)
        
        # Cleanup potential markdown wrapper
        if "```json" in response:
            response = response.split("```json")[1].split("```")[0].strip()
        elif "{" in response:
            response = "{" + response.split("{", 1)[1].rsplit("}", 1)[0] + "}"
        
        try:
            result = json.loads(response)
        except json.JSONDecodeError:
            logger.error("Guardrail Agent failed to output valid JSON.")
            result = {
                "valid": False,
                "issues_found": ["System Error: Guardrail failed to format response as JSON.", f"Raw response: {response[:100]}"],
                "fixed_output": draft_output
            }
            
        if mode == "strict" and not result.get("valid", False):
            raise ValueError(f"Output rejected by Guardrail in strict mode. Issues: {result.get('issues_found')}")
            
        return result
